import unittest
from unittest.mock import patch, MagicMock, ANY 
import sys
import os

from patent_agent.src.writing_module.api import generate_patent_section, summarize_patent, PatentDraftSection, _extract_keywords, MOCK_PATENT_DATABASE

class TestWritingModuleLLM(unittest.TestCase):

    @patch('patent_agent.src.writing_module.api._generate_content_with_llm')
    def test_generate_section_llm_success(self, mock_llm_call):
        llm_response = "This is a detailed abstract generated by an LLM about AI in drug discovery."
        mock_llm_call.return_value = llm_response
        
        prompt = "generate abstract about AI in drug discovery"
        # _extract_keywords("abstract about AI in drug discovery") -> "ai drug discovery"
        # section_title_to_generate will be "Abstract"
        result = generate_patent_section(prompt)

        mock_llm_call.assert_called_once_with("Abstract", "AI drug discovery", existing_claims=None)
        self.assertEqual(result.section_title, "Abstract")
        self.assertEqual(result.content, llm_response)
        self.assertEqual(result.confidence_score, 0.75)

    @patch('patent_agent.src.writing_module.api._generate_content_with_llm')
    def test_generate_section_llm_returns_none_fallback_to_template(self, mock_llm_call):
        mock_llm_call.return_value = None 
        
        prompt = "generate abstract about AI in drug discovery"
        expected_topic = _extract_keywords(prompt.replace("generate", "").replace("abstract", "").strip()) 
        expected_template_content = f"The present invention relates to {expected_topic}. It provides a method and system for achieving enhanced results in this field, offering significant advantages over prior art such as improved efficiency and novel functionalities."

        result = generate_patent_section(prompt)
        
        # Corrected expected_topic for the call based on how generate_patent_section prepares it
        mock_llm_call.assert_called_once_with("Abstract", "AI drug discovery", existing_claims=None)
        self.assertEqual(result.section_title, "Abstract")
        self.assertEqual(result.content, expected_template_content)
        self.assertLess(result.confidence_score, 0.5) 

    @patch('patent_agent.src.writing_module.api._generate_content_with_llm')
    def test_generate_section_llm_returns_short_content_fallback_to_template(self, mock_llm_call):
        mock_llm_call.return_value = "Too short." 
        
        prompt = "generate background for quantum sensors"
        # _extract_keywords("background for quantum sensors") -> "quantum sensors"
        # section_title_to_generate will be "Background of the Invention"
        expected_topic = _extract_keywords(prompt.replace("generate", "").replace("background", "").strip())
        expected_template_content = f"The technical field of this invention is {expected_topic}. Existing approaches in this area often suffer from limitations such as high cost, low efficiency, or excessive complexity. Therefore, there is a recognized need for an improved solution that addresses these shortcomings and advances the state of the art."


        result = generate_patent_section(prompt)
        
        mock_llm_call.assert_called_once_with("Background of the Invention", "quantum sensors", existing_claims=None)
        self.assertEqual(result.section_title, "Background of the Invention") 
        self.assertEqual(result.content, expected_template_content)
        self.assertLess(result.confidence_score, 0.5)

    @patch('patent_agent.src.writing_module.api.InferenceClient')
    @patch('patent_agent.src.writing_module.api.get_api_key')
    def test_llm_call_success_path_via_generate_patent_section(self, mock_get_api_key, mock_inference_client_constructor):
        mock_get_api_key.return_value = "fake_hf_key"
        
        mock_llm_client_instance = MagicMock()
        mock_completion = MagicMock()
        mock_completion.choices[0].message.content = " LLM generated content for abstract. "
        mock_llm_client_instance.chat.completions.create.return_value = mock_completion
        mock_inference_client_constructor.return_value = mock_llm_client_instance
        
        prompt = "generate abstract about test topic"
        result = generate_patent_section(prompt) 

        mock_get_api_key.assert_called_once_with("HUGGINGFACE_API_KEY")
        mock_inference_client_constructor.assert_called_once_with(token="fake_hf_key")
        # Check prompt construction for the LLM call
        expected_llm_prompt = (
            f"You are a patent drafting assistant. Generate a patent 'Abstract' section for an invention titled 'test topic'. "
            f"The section should be detailed, technically sound, and appropriate for a formal patent document. "
            f"For an abstract, provide a concise summary. For background, discuss prior art and problems. For summary, briefly explain the invention's advantages."
        )
        mock_llm_client_instance.chat.completions.create.assert_called_once_with(
            model="mistralai/Mistral-7B-Instruct-v0.1", 
            messages=[{"role": "user", "content": expected_llm_prompt}], 
            max_tokens=350,
            temperature=0.7
        )
        self.assertEqual(result.content, "LLM generated content for abstract.") 
        self.assertEqual(result.confidence_score, 0.75)

    @patch('patent_agent.src.writing_module.api.get_api_key')
    def test_llm_lib_not_available_fallback_via_generate_patent_section(self, mock_get_api_key):
        prompt = "generate abstract about test topic"
        expected_topic = _extract_keywords(prompt.replace("generate", "").replace("abstract", "").strip())
        expected_template_content = f"The present invention relates to {expected_topic}. It provides a method and system for achieving enhanced results in this field, offering significant advantages over prior art such as improved efficiency and novel functionalities."

        with patch('patent_agent.src.writing_module.api.InferenceClient', None):
            result = generate_patent_section(prompt)
        
        mock_get_api_key.assert_not_called() 
        self.assertEqual(result.section_title, "Abstract")
        self.assertEqual(result.content, expected_template_content)
        self.assertLess(result.confidence_score, 0.5)

    @patch('patent_agent.src.writing_module.api.InferenceClient') 
    @patch('patent_agent.src.writing_module.api.get_api_key')
    def test_llm_no_api_key_fallback_via_generate_patent_section(self, mock_get_api_key, mock_inference_client_constructor):
        mock_get_api_key.return_value = None 
        
        prompt = "generate abstract about test topic"
        expected_topic = _extract_keywords(prompt.replace("generate", "").replace("abstract", "").strip())
        expected_template_content = f"The present invention relates to {expected_topic}. It provides a method and system for achieving enhanced results in this field, offering significant advantages over prior art such as improved efficiency and novel functionalities."

        result = generate_patent_section(prompt)

        mock_get_api_key.assert_called_once_with("HUGGINGFACE_API_KEY")
        mock_inference_client_constructor.assert_not_called() 
        self.assertEqual(result.section_title, "Abstract")
        self.assertEqual(result.content, expected_template_content)
        self.assertLess(result.confidence_score, 0.5)

    @patch('patent_agent.src.writing_module.api.InferenceClient')
    @patch('patent_agent.src.writing_module.api.get_api_key')
    def test_llm_api_call_raises_exception_fallback_via_generate_patent_section(self, mock_get_api_key, mock_inference_client_constructor):
        mock_get_api_key.return_value = "fake_hf_key"
        
        mock_llm_client_instance = MagicMock()
        mock_llm_client_instance.chat.completions.create.side_effect = Exception("LLM API crashed")
        mock_inference_client_constructor.return_value = mock_llm_client_instance
        
        prompt = "generate abstract about test topic"
        expected_topic = _extract_keywords(prompt.replace("generate", "").replace("abstract", "").strip())
        expected_template_content = f"The present invention relates to {expected_topic}. It provides a method and system for achieving enhanced results in this field, offering significant advantages over prior art such as improved efficiency and novel functionalities."

        with patch('builtins.print') as mock_print: 
            result = generate_patent_section(prompt)
        
        self.assertEqual(result.section_title, "Abstract")
        self.assertEqual(result.content, expected_template_content)
        self.assertLess(result.confidence_score, 0.5)
        self.assertTrue(any("ERROR: An error occurred during LLM content generation" in call.args[0] for call in mock_print.call_args_list if call.args))


class TestWritingModuleOriginalTemplatesAndSummarize(unittest.TestCase): # Renamed class

    # Adapted tests for template-based generation (LLM fails or is unavailable)
    @patch('patent_agent.src.writing_module.api._generate_content_with_llm')
    def test_generate_patent_section_abstract_template_fallback(self, mock_llm_call):
        mock_llm_call.return_value = None # Ensure LLM part is bypassed
        prompt = "generate abstract about AI drug discovery"
        # _extract_keywords("abstract about AI drug discovery") -> "ai drug discovery"
        expected_topic = _extract_keywords(prompt.replace("generate", "").replace("abstract", "").strip())
        expected_content = f"The present invention relates to {expected_topic}. It provides a method and system for achieving enhanced results in this field, offering significant advantages over prior art such as improved efficiency and novel functionalities."
        
        result = generate_patent_section(prompt)
        self.assertIsInstance(result, PatentDraftSection)
        self.assertEqual(result.section_title, "Abstract")
        self.assertEqual(result.content, expected_content)
        self.assertEqual(result.confidence_score, 0.35) # Original template confidence

    @patch('patent_agent.src.writing_module.api._generate_content_with_llm')
    def test_generate_patent_section_background_template_fallback(self, mock_llm_call):
        mock_llm_call.return_value = None
        prompt = "generate background for synthetic biology"
        expected_topic = _extract_keywords(prompt.replace("generate", "").replace("background", "").strip())
        expected_content = f"The technical field of this invention is {expected_topic}. Existing approaches in this area often suffer from limitations such as high cost, low efficiency, or excessive complexity. Therefore, there is a recognized need for an improved solution that addresses these shortcomings and advances the state of the art."
        result = generate_patent_section(prompt)
        self.assertEqual(result.section_title, "Background of the Invention")
        self.assertEqual(result.content, expected_content)
        self.assertEqual(result.confidence_score, 0.30)


    @patch('patent_agent.src.writing_module.api._generate_content_with_llm')
    def test_generate_patent_section_summary_template_fallback(self, mock_llm_call):
        mock_llm_call.return_value = None
        prompt = "write a brief summary of a patent on biodegradable plastics"
        expected_topic = _extract_keywords(prompt.replace("write", "").replace("a brief summary of a patent on", "").strip())
        expected_content = f"The present invention provides a solution to the aforementioned problems by disclosing a novel system and method for {expected_topic}. The invention achieves superior performance and greater utility compared to existing technologies by incorporating innovative features and optimized processes."
        result = generate_patent_section(prompt)
        self.assertEqual(result.section_title, "Summary of the Invention")
        self.assertEqual(result.content, expected_content)
        self.assertEqual(result.confidence_score, 0.32)

    @patch('patent_agent.src.writing_module.api._generate_content_with_llm')
    def test_generate_patent_section_claims_no_existing_template_fallback(self, mock_llm_call):
        mock_llm_call.return_value = None
        prompt = "generate claims for a new type of solar panel"
        expected_topic = _extract_keywords(prompt.replace("generate", "").replace("claims for", "").strip())
        # Determine claim_type_text based on topic_keywords (default to "method" if "system" etc. not present)
        is_system_claim = "system" in expected_topic.lower() or "apparatus" in expected_topic.lower() or "device" in expected_topic.lower()
        is_method_claim = "method" in expected_topic.lower() or "process" in expected_topic.lower() or "technique" in expected_topic.lower()
        claim_type_text = "system" if is_system_claim and not is_method_claim else "method"
        base_claim_text = f"A {claim_type_text} for {expected_topic}, comprising:" if claim_type_text == "system" else f"A {claim_type_text} for {expected_topic}, comprising the steps of:"
        expected_content = f"1. {base_claim_text}\n   (a) a first {'component' if claim_type_text == 'system' else 'step'}; and\n   (b) a second {'component' if claim_type_text == 'system' else 'step'} operatively associated with the first {'component' if claim_type_text == 'system' else 'step'}."
        
        result = generate_patent_section(prompt)
        self.assertEqual(result.section_title, "Claims")
        self.assertEqual(result.content, expected_content)
        self.assertEqual(result.confidence_score, 0.25)

    @patch('patent_agent.src.writing_module.api._generate_content_with_llm')
    def test_generate_patent_section_claims_with_existing_template_fallback(self, mock_llm_call):
        mock_llm_call.return_value = None
        prompt = "generate claims for enhanced battery, further comprising a new electrode"
        existing_claims = ["1. A battery system comprising an anode and a cathode."]
        # Logic for additional_feature and claim_type_text from template
        additional_feature_prompt = prompt.lower().replace("generate dependent claim", "").replace("draft dependent claim", "").replace("write dependent claim","").strip()
        additional_feature = _extract_keywords(additional_feature_prompt) if "further comprising" in prompt.lower() else "an additional innovative feature"
        claim_type_text = "system" # Inferred from "battery system" in existing_claims[0]
        expected_content = f"2. The {claim_type_text} of claim 1, further comprising {additional_feature}."

        result = generate_patent_section(prompt, existing_claims=existing_claims)
        self.assertEqual(result.section_title, "Claims")
        self.assertEqual(result.content, expected_content)
        self.assertEqual(result.confidence_score, 0.25)

    @patch('patent_agent.src.writing_module.api._generate_content_with_llm')
    def test_generate_patent_section_unknown_template_fallback(self, mock_llm_call):
        mock_llm_call.return_value = None
        prompt = "tell me about nanotechnology" 
        expected_topic = _extract_keywords(prompt.replace("tell me", "").strip())
        # Fallback to general section default
        expected_content = f"Please specify a standard patent section like 'Abstract', 'Background', 'Summary', or 'Claims' for {expected_topic}."
        result = generate_patent_section(prompt)
        self.assertEqual(result.section_title, "General Section")
        self.assertEqual(result.content, expected_content)
        self.assertEqual(result.confidence_score, 0.1)

    # summarize_patent tests remain unchanged
    def test_summarize_patent_found_long_abstract(self):
        summary = summarize_patent("US20230000001A1", target_length=50)
        self.assertTrue(len(summary) <= 50 + 3) 
        self.assertTrue(summary.endswith("..."))
        original_abstract_keywords = MOCK_PATENT_DATABASE["US20230000001A1"]["abstract"].lower().split()
        summary_keywords = summary.lower().split()
        self.assertTrue(any(word in summary_keywords for word in original_abstract_keywords if len(word) > 3))

    def test_summarize_patent_found_short_abstract(self):
        short_abstract = MOCK_PATENT_DATABASE["US20220000001A1"]["abstract"]
        summary = summarize_patent("US20220000001A1", target_length=len(short_abstract) + 10)
        self.assertEqual(summary, short_abstract) 
        self.assertFalse(summary.endswith("..."))

    def test_summarize_patent_not_found(self):
        summary = summarize_patent("NOT_AN_ID_FOR_SUMMARY") # Changed ID to avoid conflict if TEMP_EMPTY_ID was used elsewhere
        self.assertIn("not found", summary)
        
    def test_summarize_patent_empty_abstract(self):
        original_patent_data = MOCK_PATENT_DATABASE.get("TEMP_EMPTY_ID_SUMM") # Unique ID for this test
        MOCK_PATENT_DATABASE["TEMP_EMPTY_ID_SUMM"] = {"patent_id": "TEMP_EMPTY_ID_SUMM", "title": "Test Empty Summary", "abstract": " "}
        summary = summarize_patent("TEMP_EMPTY_ID_SUMM", target_length=50)
        self.assertEqual(summary, "No abstract content available to summarize.")
        if original_patent_data is None: 
            if "TEMP_EMPTY_ID_SUMM" in MOCK_PATENT_DATABASE:
                 del MOCK_PATENT_DATABASE["TEMP_EMPTY_ID_SUMM"]
        else: 
             MOCK_PATENT_DATABASE["TEMP_EMPTY_ID_SUMM"] = original_patent_data

if __name__ == '__main__':
    unittest.main()
